# Site Info
locale: "id-ID"
title_separator: "-"
title: Putra Binangkit
tagline: 'Layanan Informasi & Teknologi'
description: 'Layanan professional Informasi & Teknologi untuk organisasi, bisnis dan perorangan'
baseurl: '/'
breadcrumbs: true
url: https://www.putrabinangkit.com
logo: '/img/logo-atas-black.png'

# Site configurations
gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 1
paginate_path: 'blog/page:num'
permalink: blog/:title/

# About/contact
author:
  name: Putra Binangkit
  description: Layanan Informasi & Teknologi.
  contact:
    #linkedin:  <hide>
    github: https://github.com/PutraBinangkit
    # facebook:  <hide>
    #twitter:   <hide>
    #weibo:     <hide>
    #email:     <hide>

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'